import type { SelectOption } from "naive-ui"
import type { adminDivResult } from "@/type/admin-div.ts"

export const allCities: adminDivResult[] = [
  {
    name: "北京市",
    code: 1101,
    parent_code: 11,
    pinyin_prefix: "b",
  },
  {
    name: "天津市",
    code: 1201,
    parent_code: 12,
    pinyin_prefix: "t",
  },
  {
    name: "石家庄市",
    code: 1301,
    parent_code: 13,
    pinyin_prefix: "s",
  },
  {
    name: "唐山市",
    code: 1302,
    parent_code: 13,
    pinyin_prefix: "t",
  },
  {
    name: "秦皇岛市",
    code: 1303,
    parent_code: 13,
    pinyin_prefix: "q",
  },
  {
    name: "邯郸市",
    code: 1304,
    parent_code: 13,
    pinyin_prefix: "h",
  },
  {
    name: "邢台市",
    code: 1305,
    parent_code: 13,
    pinyin_prefix: "x",
  },
  {
    name: "保定市",
    code: 1306,
    parent_code: 13,
    pinyin_prefix: "b",
  },
  {
    name: "张家口市",
    code: 1307,
    parent_code: 13,
    pinyin_prefix: "z",
  },
  {
    name: "承德市",
    code: 1308,
    parent_code: 13,
    pinyin_prefix: "c",
  },
  {
    name: "沧州市",
    code: 1309,
    parent_code: 13,
    pinyin_prefix: "c",
  },
  {
    name: "廊坊市",
    code: 1310,
    parent_code: 13,
    pinyin_prefix: "l",
  },
  {
    name: "衡水市",
    code: 1311,
    parent_code: 13,
    pinyin_prefix: "h",
  },
  {
    name: "太原市",
    code: 1401,
    parent_code: 14,
    pinyin_prefix: "t",
  },
  {
    name: "大同市",
    code: 1402,
    parent_code: 14,
    pinyin_prefix: "d",
  },
  {
    name: "阳泉市",
    code: 1403,
    parent_code: 14,
    pinyin_prefix: "y",
  },
  {
    name: "长治市",
    code: 1404,
    parent_code: 14,
    pinyin_prefix: "c",
  },
  {
    name: "晋城市",
    code: 1405,
    parent_code: 14,
    pinyin_prefix: "j",
  },
  {
    name: "朔州市",
    code: 1406,
    parent_code: 14,
    pinyin_prefix: "s",
  },
  {
    name: "晋中市",
    code: 1407,
    parent_code: 14,
    pinyin_prefix: "j",
  },
  {
    name: "运城市",
    code: 1408,
    parent_code: 14,
    pinyin_prefix: "y",
  },
  {
    name: "忻州市",
    code: 1409,
    parent_code: 14,
    pinyin_prefix: "x",
  },
  {
    name: "临汾市",
    code: 1410,
    parent_code: 14,
    pinyin_prefix: "l",
  },
  {
    name: "吕梁市",
    code: 1411,
    parent_code: 14,
    pinyin_prefix: "l",
  },
  {
    name: "呼和浩特市",
    code: 1501,
    parent_code: 15,
    pinyin_prefix: "h",
  },
  {
    name: "包头市",
    code: 1502,
    parent_code: 15,
    pinyin_prefix: "b",
  },
  {
    name: "乌海市",
    code: 1503,
    parent_code: 15,
    pinyin_prefix: "w",
  },
  {
    name: "赤峰市",
    code: 1504,
    parent_code: 15,
    pinyin_prefix: "c",
  },
  {
    name: "通辽市",
    code: 1505,
    parent_code: 15,
    pinyin_prefix: "t",
  },
  {
    name: "鄂尔多斯市",
    code: 1506,
    parent_code: 15,
    pinyin_prefix: "e",
  },
  {
    name: "呼伦贝尔市",
    code: 1507,
    parent_code: 15,
    pinyin_prefix: "h",
  },
  {
    name: "巴彦淖尔市",
    code: 1508,
    parent_code: 15,
    pinyin_prefix: "b",
  },
  {
    name: "乌兰察布市",
    code: 1509,
    parent_code: 15,
    pinyin_prefix: "w",
  },
  {
    name: "兴安盟",
    code: 1522,
    parent_code: 15,
    pinyin_prefix: "x",
  },
  {
    name: "锡林郭勒盟",
    code: 1525,
    parent_code: 15,
    pinyin_prefix: "x",
  },
  {
    name: "阿拉善盟",
    code: 1529,
    parent_code: 15,
    pinyin_prefix: "a",
  },
  {
    name: "沈阳市",
    code: 2101,
    parent_code: 21,
    pinyin_prefix: "s",
  },
  {
    name: "大连市",
    code: 2102,
    parent_code: 21,
    pinyin_prefix: "d",
  },
  {
    name: "鞍山市",
    code: 2103,
    parent_code: 21,
    pinyin_prefix: "a",
  },
  {
    name: "抚顺市",
    code: 2104,
    parent_code: 21,
    pinyin_prefix: "f",
  },
  {
    name: "本溪市",
    code: 2105,
    parent_code: 21,
    pinyin_prefix: "b",
  },
  {
    name: "丹东市",
    code: 2106,
    parent_code: 21,
    pinyin_prefix: "d",
  },
  {
    name: "锦州市",
    code: 2107,
    parent_code: 21,
    pinyin_prefix: "j",
  },
  {
    name: "营口市",
    code: 2108,
    parent_code: 21,
    pinyin_prefix: "y",
  },
  {
    name: "阜新市",
    code: 2109,
    parent_code: 21,
    pinyin_prefix: "f",
  },
  {
    name: "辽阳市",
    code: 2110,
    parent_code: 21,
    pinyin_prefix: "l",
  },
  {
    name: "盘锦市",
    code: 2111,
    parent_code: 21,
    pinyin_prefix: "p",
  },
  {
    name: "铁岭市",
    code: 2112,
    parent_code: 21,
    pinyin_prefix: "t",
  },
  {
    name: "朝阳市",
    code: 2113,
    parent_code: 21,
    pinyin_prefix: "c",
  },
  {
    name: "葫芦岛市",
    code: 2114,
    parent_code: 21,
    pinyin_prefix: "h",
  },
  {
    name: "长春市",
    code: 2201,
    parent_code: 22,
    pinyin_prefix: "c",
  },
  {
    name: "吉林市",
    code: 2202,
    parent_code: 22,
    pinyin_prefix: "j",
  },
  {
    name: "四平市",
    code: 2203,
    parent_code: 22,
    pinyin_prefix: "s",
  },
  {
    name: "辽源市",
    code: 2204,
    parent_code: 22,
    pinyin_prefix: "l",
  },
  {
    name: "通化市",
    code: 2205,
    parent_code: 22,
    pinyin_prefix: "t",
  },
  {
    name: "白山市",
    code: 2206,
    parent_code: 22,
    pinyin_prefix: "b",
  },
  {
    name: "松原市",
    code: 2207,
    parent_code: 22,
    pinyin_prefix: "s",
  },
  {
    name: "白城市",
    code: 2208,
    parent_code: 22,
    pinyin_prefix: "b",
  },
  {
    name: "延边朝鲜族自治州",
    code: 2224,
    parent_code: 22,
    pinyin_prefix: "y",
  },
  {
    name: "哈尔滨市",
    code: 2301,
    parent_code: 23,
    pinyin_prefix: "h",
  },
  {
    name: "齐齐哈尔市",
    code: 2302,
    parent_code: 23,
    pinyin_prefix: "q",
  },
  {
    name: "鸡西市",
    code: 2303,
    parent_code: 23,
    pinyin_prefix: "j",
  },
  {
    name: "鹤岗市",
    code: 2304,
    parent_code: 23,
    pinyin_prefix: "h",
  },
  {
    name: "双鸭山市",
    code: 2305,
    parent_code: 23,
    pinyin_prefix: "s",
  },
  {
    name: "大庆市",
    code: 2306,
    parent_code: 23,
    pinyin_prefix: "d",
  },
  {
    name: "伊春市",
    code: 2307,
    parent_code: 23,
    pinyin_prefix: "y",
  },
  {
    name: "佳木斯市",
    code: 2308,
    parent_code: 23,
    pinyin_prefix: "j",
  },
  {
    name: "七台河市",
    code: 2309,
    parent_code: 23,
    pinyin_prefix: "q",
  },
  {
    name: "牡丹江市",
    code: 2310,
    parent_code: 23,
    pinyin_prefix: "m",
  },
  {
    name: "黑河市",
    code: 2311,
    parent_code: 23,
    pinyin_prefix: "h",
  },
  {
    name: "绥化市",
    code: 2312,
    parent_code: 23,
    pinyin_prefix: "s",
  },
  {
    name: "大兴安岭地区",
    code: 2327,
    parent_code: 23,
    pinyin_prefix: "d",
  },
  {
    name: "上海市",
    code: 3101,
    parent_code: 31,
    pinyin_prefix: "s",
  },
  {
    name: "南京市",
    code: 3201,
    parent_code: 32,
    pinyin_prefix: "n",
  },
  {
    name: "无锡市",
    code: 3202,
    parent_code: 32,
    pinyin_prefix: "w",
  },
  {
    name: "徐州市",
    code: 3203,
    parent_code: 32,
    pinyin_prefix: "x",
  },
  {
    name: "常州市",
    code: 3204,
    parent_code: 32,
    pinyin_prefix: "c",
  },
  {
    name: "苏州市",
    code: 3205,
    parent_code: 32,
    pinyin_prefix: "s",
  },
  {
    name: "南通市",
    code: 3206,
    parent_code: 32,
    pinyin_prefix: "n",
  },
  {
    name: "连云港市",
    code: 3207,
    parent_code: 32,
    pinyin_prefix: "l",
  },
  {
    name: "淮安市",
    code: 3208,
    parent_code: 32,
    pinyin_prefix: "h",
  },
  {
    name: "盐城市",
    code: 3209,
    parent_code: 32,
    pinyin_prefix: "y",
  },
  {
    name: "扬州市",
    code: 3210,
    parent_code: 32,
    pinyin_prefix: "y",
  },
  {
    name: "镇江市",
    code: 3211,
    parent_code: 32,
    pinyin_prefix: "z",
  },
  {
    name: "泰州市",
    code: 3212,
    parent_code: 32,
    pinyin_prefix: "t",
  },
  {
    name: "宿迁市",
    code: 3213,
    parent_code: 32,
    pinyin_prefix: "s",
  },
  {
    name: "杭州市",
    code: 3301,
    parent_code: 33,
    pinyin_prefix: "h",
  },
  {
    name: "宁波市",
    code: 3302,
    parent_code: 33,
    pinyin_prefix: "n",
  },
  {
    name: "温州市",
    code: 3303,
    parent_code: 33,
    pinyin_prefix: "w",
  },
  {
    name: "嘉兴市",
    code: 3304,
    parent_code: 33,
    pinyin_prefix: "j",
  },
  {
    name: "湖州市",
    code: 3305,
    parent_code: 33,
    pinyin_prefix: "h",
  },
  {
    name: "绍兴市",
    code: 3306,
    parent_code: 33,
    pinyin_prefix: "s",
  },
  {
    name: "金华市",
    code: 3307,
    parent_code: 33,
    pinyin_prefix: "j",
  },
  {
    name: "衢州市",
    code: 3308,
    parent_code: 33,
    pinyin_prefix: "q",
  },
  {
    name: "舟山市",
    code: 3309,
    parent_code: 33,
    pinyin_prefix: "z",
  },
  {
    name: "台州市",
    code: 3310,
    parent_code: 33,
    pinyin_prefix: "t",
  },
  {
    name: "丽水市",
    code: 3311,
    parent_code: 33,
    pinyin_prefix: "l",
  },
  {
    name: "合肥市",
    code: 3401,
    parent_code: 34,
    pinyin_prefix: "h",
  },
  {
    name: "芜湖市",
    code: 3402,
    parent_code: 34,
    pinyin_prefix: "w",
  },
  {
    name: "蚌埠市",
    code: 3403,
    parent_code: 34,
    pinyin_prefix: "b",
  },
  {
    name: "淮南市",
    code: 3404,
    parent_code: 34,
    pinyin_prefix: "h",
  },
  {
    name: "马鞍山市",
    code: 3405,
    parent_code: 34,
    pinyin_prefix: "m",
  },
  {
    name: "淮北市",
    code: 3406,
    parent_code: 34,
    pinyin_prefix: "h",
  },
  {
    name: "铜陵市",
    code: 3407,
    parent_code: 34,
    pinyin_prefix: "t",
  },
  {
    name: "安庆市",
    code: 3408,
    parent_code: 34,
    pinyin_prefix: "a",
  },
  {
    name: "黄山市",
    code: 3410,
    parent_code: 34,
    pinyin_prefix: "h",
  },
  {
    name: "滁州市",
    code: 3411,
    parent_code: 34,
    pinyin_prefix: "c",
  },
  {
    name: "阜阳市",
    code: 3412,
    parent_code: 34,
    pinyin_prefix: "f",
  },
  {
    name: "宿州市",
    code: 3413,
    parent_code: 34,
    pinyin_prefix: "s",
  },
  {
    name: "六安市",
    code: 3415,
    parent_code: 34,
    pinyin_prefix: "l",
  },
  {
    name: "亳州市",
    code: 3416,
    parent_code: 34,
    pinyin_prefix: "b",
  },
  {
    name: "池州市",
    code: 3417,
    parent_code: 34,
    pinyin_prefix: "c",
  },
  {
    name: "宣城市",
    code: 3418,
    parent_code: 34,
    pinyin_prefix: "x",
  },
  {
    name: "福州市",
    code: 3501,
    parent_code: 35,
    pinyin_prefix: "f",
  },
  {
    name: "厦门市",
    code: 3502,
    parent_code: 35,
    pinyin_prefix: "x",
  },
  {
    name: "莆田市",
    code: 3503,
    parent_code: 35,
    pinyin_prefix: "p",
  },
  {
    name: "三明市",
    code: 3504,
    parent_code: 35,
    pinyin_prefix: "s",
  },
  {
    name: "泉州市",
    code: 3505,
    parent_code: 35,
    pinyin_prefix: "q",
  },
  {
    name: "漳州市",
    code: 3506,
    parent_code: 35,
    pinyin_prefix: "z",
  },
  {
    name: "南平市",
    code: 3507,
    parent_code: 35,
    pinyin_prefix: "n",
  },
  {
    name: "龙岩市",
    code: 3508,
    parent_code: 35,
    pinyin_prefix: "l",
  },
  {
    name: "宁德市",
    code: 3509,
    parent_code: 35,
    pinyin_prefix: "n",
  },
  {
    name: "南昌市",
    code: 3601,
    parent_code: 36,
    pinyin_prefix: "n",
  },
  {
    name: "景德镇市",
    code: 3602,
    parent_code: 36,
    pinyin_prefix: "j",
  },
  {
    name: "萍乡市",
    code: 3603,
    parent_code: 36,
    pinyin_prefix: "p",
  },
  {
    name: "九江市",
    code: 3604,
    parent_code: 36,
    pinyin_prefix: "j",
  },
  {
    name: "新余市",
    code: 3605,
    parent_code: 36,
    pinyin_prefix: "x",
  },
  {
    name: "鹰潭市",
    code: 3606,
    parent_code: 36,
    pinyin_prefix: "y",
  },
  {
    name: "赣州市",
    code: 3607,
    parent_code: 36,
    pinyin_prefix: "g",
  },
  {
    name: "吉安市",
    code: 3608,
    parent_code: 36,
    pinyin_prefix: "j",
  },
  {
    name: "宜春市",
    code: 3609,
    parent_code: 36,
    pinyin_prefix: "y",
  },
  {
    name: "抚州市",
    code: 3610,
    parent_code: 36,
    pinyin_prefix: "f",
  },
  {
    name: "上饶市",
    code: 3611,
    parent_code: 36,
    pinyin_prefix: "s",
  },
  {
    name: "济南市",
    code: 3701,
    parent_code: 37,
    pinyin_prefix: "j",
  },
  {
    name: "青岛市",
    code: 3702,
    parent_code: 37,
    pinyin_prefix: "q",
  },
  {
    name: "淄博市",
    code: 3703,
    parent_code: 37,
    pinyin_prefix: "z",
  },
  {
    name: "枣庄市",
    code: 3704,
    parent_code: 37,
    pinyin_prefix: "z",
  },
  {
    name: "东营市",
    code: 3705,
    parent_code: 37,
    pinyin_prefix: "d",
  },
  {
    name: "烟台市",
    code: 3706,
    parent_code: 37,
    pinyin_prefix: "y",
  },
  {
    name: "潍坊市",
    code: 3707,
    parent_code: 37,
    pinyin_prefix: "w",
  },
  {
    name: "济宁市",
    code: 3708,
    parent_code: 37,
    pinyin_prefix: "j",
  },
  {
    name: "泰安市",
    code: 3709,
    parent_code: 37,
    pinyin_prefix: "t",
  },
  {
    name: "威海市",
    code: 3710,
    parent_code: 37,
    pinyin_prefix: "w",
  },
  {
    name: "日照市",
    code: 3711,
    parent_code: 37,
    pinyin_prefix: "r",
  },
  {
    name: "临沂市",
    code: 3713,
    parent_code: 37,
    pinyin_prefix: "l",
  },
  {
    name: "德州市",
    code: 3714,
    parent_code: 37,
    pinyin_prefix: "d",
  },
  {
    name: "聊城市",
    code: 3715,
    parent_code: 37,
    pinyin_prefix: "l",
  },
  {
    name: "滨州市",
    code: 3716,
    parent_code: 37,
    pinyin_prefix: "b",
  },
  {
    name: "菏泽市",
    code: 3717,
    parent_code: 37,
    pinyin_prefix: "h",
  },
  {
    name: "郑州市",
    code: 4101,
    parent_code: 41,
    pinyin_prefix: "z",
  },
  {
    name: "开封市",
    code: 4102,
    parent_code: 41,
    pinyin_prefix: "k",
  },
  {
    name: "洛阳市",
    code: 4103,
    parent_code: 41,
    pinyin_prefix: "l",
  },
  {
    name: "平顶山市",
    code: 4104,
    parent_code: 41,
    pinyin_prefix: "p",
  },
  {
    name: "安阳市",
    code: 4105,
    parent_code: 41,
    pinyin_prefix: "a",
  },
  {
    name: "鹤壁市",
    code: 4106,
    parent_code: 41,
    pinyin_prefix: "h",
  },
  {
    name: "新乡市",
    code: 4107,
    parent_code: 41,
    pinyin_prefix: "x",
  },
  {
    name: "焦作市",
    code: 4108,
    parent_code: 41,
    pinyin_prefix: "j",
  },
  {
    name: "濮阳市",
    code: 4109,
    parent_code: 41,
    pinyin_prefix: "p",
  },
  {
    name: "许昌市",
    code: 4110,
    parent_code: 41,
    pinyin_prefix: "x",
  },
  {
    name: "漯河市",
    code: 4111,
    parent_code: 41,
    pinyin_prefix: "l",
  },
  {
    name: "三门峡市",
    code: 4112,
    parent_code: 41,
    pinyin_prefix: "s",
  },
  {
    name: "南阳市",
    code: 4113,
    parent_code: 41,
    pinyin_prefix: "n",
  },
  {
    name: "商丘市",
    code: 4114,
    parent_code: 41,
    pinyin_prefix: "s",
  },
  {
    name: "信阳市",
    code: 4115,
    parent_code: 41,
    pinyin_prefix: "x",
  },
  {
    name: "周口市",
    code: 4116,
    parent_code: 41,
    pinyin_prefix: "z",
  },
  {
    name: "驻马店市",
    code: 4117,
    parent_code: 41,
    pinyin_prefix: "z",
  },
  {
    name: "济源市",
    code: 419001,
    parent_code: 41,
    pinyin_prefix: "j",
  },
  {
    name: "武汉市",
    code: 4201,
    parent_code: 42,
    pinyin_prefix: "w",
  },
  {
    name: "黄石市",
    code: 4202,
    parent_code: 42,
    pinyin_prefix: "h",
  },
  {
    name: "十堰市",
    code: 4203,
    parent_code: 42,
    pinyin_prefix: "s",
  },
  {
    name: "宜昌市",
    code: 4205,
    parent_code: 42,
    pinyin_prefix: "y",
  },
  {
    name: "襄阳市",
    code: 4206,
    parent_code: 42,
    pinyin_prefix: "x",
  },
  {
    name: "鄂州市",
    code: 4207,
    parent_code: 42,
    pinyin_prefix: "e",
  },
  {
    name: "荆门市",
    code: 4208,
    parent_code: 42,
    pinyin_prefix: "j",
  },
  {
    name: "孝感市",
    code: 4209,
    parent_code: 42,
    pinyin_prefix: "x",
  },
  {
    name: "荆州市",
    code: 4210,
    parent_code: 42,
    pinyin_prefix: "j",
  },
  {
    name: "黄冈市",
    code: 4211,
    parent_code: 42,
    pinyin_prefix: "h",
  },
  {
    name: "咸宁市",
    code: 4212,
    parent_code: 42,
    pinyin_prefix: "x",
  },
  {
    name: "随州市",
    code: 4213,
    parent_code: 42,
    pinyin_prefix: "s",
  },
  {
    name: "恩施土家族苗族自治州",
    code: 4228,
    parent_code: 42,
    pinyin_prefix: "e",
  },
  {
    name: "仙桃市",
    code: 429004,
    parent_code: 42,
    pinyin_prefix: "x",
  },
  {
    name: "潜江市",
    code: 429005,
    parent_code: 42,
    pinyin_prefix: "q",
  },
  {
    name: "天门市",
    code: 429006,
    parent_code: 42,
    pinyin_prefix: "t",
  },
  {
    name: "神农架林区",
    code: 429021,
    parent_code: 42,
    pinyin_prefix: "s",
  },
  {
    name: "长沙市",
    code: 4301,
    parent_code: 43,
    pinyin_prefix: "c",
  },
  {
    name: "株洲市",
    code: 4302,
    parent_code: 43,
    pinyin_prefix: "z",
  },
  {
    name: "湘潭市",
    code: 4303,
    parent_code: 43,
    pinyin_prefix: "x",
  },
  {
    name: "衡阳市",
    code: 4304,
    parent_code: 43,
    pinyin_prefix: "h",
  },
  {
    name: "邵阳市",
    code: 4305,
    parent_code: 43,
    pinyin_prefix: "s",
  },
  {
    name: "岳阳市",
    code: 4306,
    parent_code: 43,
    pinyin_prefix: "y",
  },
  {
    name: "常德市",
    code: 4307,
    parent_code: 43,
    pinyin_prefix: "c",
  },
  {
    name: "张家界市",
    code: 4308,
    parent_code: 43,
    pinyin_prefix: "z",
  },
  {
    name: "益阳市",
    code: 4309,
    parent_code: 43,
    pinyin_prefix: "y",
  },
  {
    name: "郴州市",
    code: 4310,
    parent_code: 43,
    pinyin_prefix: "c",
  },
  {
    name: "永州市",
    code: 4311,
    parent_code: 43,
    pinyin_prefix: "y",
  },
  {
    name: "怀化市",
    code: 4312,
    parent_code: 43,
    pinyin_prefix: "h",
  },
  {
    name: "娄底市",
    code: 4313,
    parent_code: 43,
    pinyin_prefix: "l",
  },
  {
    name: "湘西土家族苗族自治州",
    code: 4331,
    parent_code: 43,
    pinyin_prefix: "x",
  },
  {
    name: "广州市",
    code: 4401,
    parent_code: 44,
    pinyin_prefix: "g",
  },
  {
    name: "韶关市",
    code: 4402,
    parent_code: 44,
    pinyin_prefix: "s",
  },
  {
    name: "深圳市",
    code: 4403,
    parent_code: 44,
    pinyin_prefix: "s",
  },
  {
    name: "珠海市",
    code: 4404,
    parent_code: 44,
    pinyin_prefix: "z",
  },
  {
    name: "汕头市",
    code: 4405,
    parent_code: 44,
    pinyin_prefix: "s",
  },
  {
    name: "佛山市",
    code: 4406,
    parent_code: 44,
    pinyin_prefix: "f",
  },
  {
    name: "江门市",
    code: 4407,
    parent_code: 44,
    pinyin_prefix: "j",
  },
  {
    name: "湛江市",
    code: 4408,
    parent_code: 44,
    pinyin_prefix: "z",
  },
  {
    name: "茂名市",
    code: 4409,
    parent_code: 44,
    pinyin_prefix: "m",
  },
  {
    name: "肇庆市",
    code: 4412,
    parent_code: 44,
    pinyin_prefix: "z",
  },
  {
    name: "惠州市",
    code: 4413,
    parent_code: 44,
    pinyin_prefix: "h",
  },
  {
    name: "梅州市",
    code: 4414,
    parent_code: 44,
    pinyin_prefix: "m",
  },
  {
    name: "汕尾市",
    code: 4415,
    parent_code: 44,
    pinyin_prefix: "s",
  },
  {
    name: "河源市",
    code: 4416,
    parent_code: 44,
    pinyin_prefix: "h",
  },
  {
    name: "阳江市",
    code: 4417,
    parent_code: 44,
    pinyin_prefix: "y",
  },
  {
    name: "清远市",
    code: 4418,
    parent_code: 44,
    pinyin_prefix: "q",
  },
  {
    name: "东莞市",
    code: 4419,
    parent_code: 44,
    pinyin_prefix: "d",
  },
  {
    name: "中山市",
    code: 4420,
    parent_code: 44,
    pinyin_prefix: "z",
  },
  {
    name: "潮州市",
    code: 4451,
    parent_code: 44,
    pinyin_prefix: "c",
  },
  {
    name: "揭阳市",
    code: 4452,
    parent_code: 44,
    pinyin_prefix: "j",
  },
  {
    name: "云浮市",
    code: 4453,
    parent_code: 44,
    pinyin_prefix: "y",
  },
  {
    name: "南宁市",
    code: 4501,
    parent_code: 45,
    pinyin_prefix: "n",
  },
  {
    name: "柳州市",
    code: 4502,
    parent_code: 45,
    pinyin_prefix: "l",
  },
  {
    name: "桂林市",
    code: 4503,
    parent_code: 45,
    pinyin_prefix: "g",
  },
  {
    name: "梧州市",
    code: 4504,
    parent_code: 45,
    pinyin_prefix: "w",
  },
  {
    name: "北海市",
    code: 4505,
    parent_code: 45,
    pinyin_prefix: "b",
  },
  {
    name: "防城港市",
    code: 4506,
    parent_code: 45,
    pinyin_prefix: "f",
  },
  {
    name: "钦州市",
    code: 4507,
    parent_code: 45,
    pinyin_prefix: "q",
  },
  {
    name: "贵港市",
    code: 4508,
    parent_code: 45,
    pinyin_prefix: "g",
  },
  {
    name: "玉林市",
    code: 4509,
    parent_code: 45,
    pinyin_prefix: "y",
  },
  {
    name: "百色市",
    code: 4510,
    parent_code: 45,
    pinyin_prefix: "b",
  },
  {
    name: "贺州市",
    code: 4511,
    parent_code: 45,
    pinyin_prefix: "h",
  },
  {
    name: "河池市",
    code: 4512,
    parent_code: 45,
    pinyin_prefix: "h",
  },
  {
    name: "来宾市",
    code: 4513,
    parent_code: 45,
    pinyin_prefix: "l",
  },
  {
    name: "崇左市",
    code: 4514,
    parent_code: 45,
    pinyin_prefix: "c",
  },
  {
    name: "海口市",
    code: 4601,
    parent_code: 46,
    pinyin_prefix: "h",
  },
  {
    name: "三亚市",
    code: 4602,
    parent_code: 46,
    pinyin_prefix: "s",
  },
  {
    name: "三沙市",
    code: 4603,
    parent_code: 46,
    pinyin_prefix: "s",
  },
  {
    name: "儋州市",
    code: 4604,
    parent_code: 46,
    pinyin_prefix: "d",
  },
  {
    name: "五指山市",
    code: 469001,
    parent_code: 46,
    pinyin_prefix: "w",
  },
  {
    name: "琼海市",
    code: 469002,
    parent_code: 46,
    pinyin_prefix: "q",
  },
  {
    name: "文昌市",
    code: 469005,
    parent_code: 46,
    pinyin_prefix: "w",
  },
  {
    name: "万宁市",
    code: 469006,
    parent_code: 46,
    pinyin_prefix: "w",
  },
  {
    name: "东方市",
    code: 469007,
    parent_code: 46,
    pinyin_prefix: "d",
  },
  {
    name: "定安县",
    code: 469021,
    parent_code: 46,
    pinyin_prefix: "d",
  },
  {
    name: "屯昌县",
    code: 469022,
    parent_code: 46,
    pinyin_prefix: "t",
  },
  {
    name: "澄迈县",
    code: 469023,
    parent_code: 46,
    pinyin_prefix: "c",
  },
  {
    name: "临高县",
    code: 469024,
    parent_code: 46,
    pinyin_prefix: "l",
  },
  {
    name: "白沙黎族自治县",
    code: 469025,
    parent_code: 46,
    pinyin_prefix: "b",
  },
  {
    name: "昌江黎族自治县",
    code: 469026,
    parent_code: 46,
    pinyin_prefix: "c",
  },
  {
    name: "乐东黎族自治县",
    code: 469027,
    parent_code: 46,
    pinyin_prefix: "l",
  },
  {
    name: "陵水黎族自治县",
    code: 469028,
    parent_code: 46,
    pinyin_prefix: "l",
  },
  {
    name: "保亭黎族苗族自治县",
    code: 469029,
    parent_code: 46,
    pinyin_prefix: "b",
  },
  {
    name: "琼中黎族苗族自治县",
    code: 469030,
    parent_code: 46,
    pinyin_prefix: "q",
  },
  {
    name: "重庆城区",
    code: 5001,
    parent_code: 50,
    pinyin_prefix: "c",
  },
  {
    name: "重庆郊县",
    code: 5002,
    parent_code: 50,
    pinyin_prefix: "c",
  },
  {
    name: "成都市",
    code: 5101,
    parent_code: 51,
    pinyin_prefix: "c",
  },
  {
    name: "自贡市",
    code: 5103,
    parent_code: 51,
    pinyin_prefix: "z",
  },
  {
    name: "攀枝花市",
    code: 5104,
    parent_code: 51,
    pinyin_prefix: "p",
  },
  {
    name: "泸州市",
    code: 5105,
    parent_code: 51,
    pinyin_prefix: "l",
  },
  {
    name: "德阳市",
    code: 5106,
    parent_code: 51,
    pinyin_prefix: "d",
  },
  {
    name: "绵阳市",
    code: 5107,
    parent_code: 51,
    pinyin_prefix: "m",
  },
  {
    name: "广元市",
    code: 5108,
    parent_code: 51,
    pinyin_prefix: "g",
  },
  {
    name: "遂宁市",
    code: 5109,
    parent_code: 51,
    pinyin_prefix: "s",
  },
  {
    name: "内江市",
    code: 5110,
    parent_code: 51,
    pinyin_prefix: "n",
  },
  {
    name: "乐山市",
    code: 5111,
    parent_code: 51,
    pinyin_prefix: "l",
  },
  {
    name: "南充市",
    code: 5113,
    parent_code: 51,
    pinyin_prefix: "n",
  },
  {
    name: "眉山市",
    code: 5114,
    parent_code: 51,
    pinyin_prefix: "m",
  },
  {
    name: "宜宾市",
    code: 5115,
    parent_code: 51,
    pinyin_prefix: "y",
  },
  {
    name: "广安市",
    code: 5116,
    parent_code: 51,
    pinyin_prefix: "g",
  },
  {
    name: "达州市",
    code: 5117,
    parent_code: 51,
    pinyin_prefix: "d",
  },
  {
    name: "雅安市",
    code: 5118,
    parent_code: 51,
    pinyin_prefix: "y",
  },
  {
    name: "巴中市",
    code: 5119,
    parent_code: 51,
    pinyin_prefix: "b",
  },
  {
    name: "资阳市",
    code: 5120,
    parent_code: 51,
    pinyin_prefix: "z",
  },
  {
    name: "阿坝藏族羌族自治州",
    code: 5132,
    parent_code: 51,
    pinyin_prefix: "a",
  },
  {
    name: "甘孜藏族自治州",
    code: 5133,
    parent_code: 51,
    pinyin_prefix: "g",
  },
  {
    name: "凉山彝族自治州",
    code: 5134,
    parent_code: 51,
    pinyin_prefix: "l",
  },
  {
    name: "贵阳市",
    code: 5201,
    parent_code: 52,
    pinyin_prefix: "g",
  },
  {
    name: "六盘水市",
    code: 5202,
    parent_code: 52,
    pinyin_prefix: "l",
  },
  {
    name: "遵义市",
    code: 5203,
    parent_code: 52,
    pinyin_prefix: "z",
  },
  {
    name: "安顺市",
    code: 5204,
    parent_code: 52,
    pinyin_prefix: "a",
  },
  {
    name: "毕节市",
    code: 5205,
    parent_code: 52,
    pinyin_prefix: "b",
  },
  {
    name: "铜仁市",
    code: 5206,
    parent_code: 52,
    pinyin_prefix: "t",
  },
  {
    name: "黔西南布依族苗族自治州",
    code: 5223,
    parent_code: 52,
    pinyin_prefix: "q",
  },
  {
    name: "黔东南苗族侗族自治州",
    code: 5226,
    parent_code: 52,
    pinyin_prefix: "q",
  },
  {
    name: "黔南布依族苗族自治州",
    code: 5227,
    parent_code: 52,
    pinyin_prefix: "q",
  },
  {
    name: "昆明市",
    code: 5301,
    parent_code: 53,
    pinyin_prefix: "k",
  },
  {
    name: "曲靖市",
    code: 5303,
    parent_code: 53,
    pinyin_prefix: "q",
  },
  {
    name: "玉溪市",
    code: 5304,
    parent_code: 53,
    pinyin_prefix: "y",
  },
  {
    name: "保山市",
    code: 5305,
    parent_code: 53,
    pinyin_prefix: "b",
  },
  {
    name: "昭通市",
    code: 5306,
    parent_code: 53,
    pinyin_prefix: "z",
  },
  {
    name: "丽江市",
    code: 5307,
    parent_code: 53,
    pinyin_prefix: "l",
  },
  {
    name: "普洱市",
    code: 5308,
    parent_code: 53,
    pinyin_prefix: "p",
  },
  {
    name: "临沧市",
    code: 5309,
    parent_code: 53,
    pinyin_prefix: "l",
  },
  {
    name: "楚雄彝族自治州",
    code: 5323,
    parent_code: 53,
    pinyin_prefix: "c",
  },
  {
    name: "红河哈尼族彝族自治州",
    code: 5325,
    parent_code: 53,
    pinyin_prefix: "h",
  },
  {
    name: "文山壮族苗族自治州",
    code: 5326,
    parent_code: 53,
    pinyin_prefix: "w",
  },
  {
    name: "西双版纳傣族自治州",
    code: 5328,
    parent_code: 53,
    pinyin_prefix: "x",
  },
  {
    name: "大理白族自治州",
    code: 5329,
    parent_code: 53,
    pinyin_prefix: "d",
  },
  {
    name: "德宏傣族景颇族自治州",
    code: 5331,
    parent_code: 53,
    pinyin_prefix: "d",
  },
  {
    name: "怒江傈僳族自治州",
    code: 5333,
    parent_code: 53,
    pinyin_prefix: "n",
  },
  {
    name: "迪庆藏族自治州",
    code: 5334,
    parent_code: 53,
    pinyin_prefix: "d",
  },
  {
    name: "拉萨市",
    code: 5401,
    parent_code: 54,
    pinyin_prefix: "l",
  },
  {
    name: "日喀则市",
    code: 5402,
    parent_code: 54,
    pinyin_prefix: "r",
  },
  {
    name: "昌都市",
    code: 5403,
    parent_code: 54,
    pinyin_prefix: "c",
  },
  {
    name: "林芝市",
    code: 5404,
    parent_code: 54,
    pinyin_prefix: "l",
  },
  {
    name: "山南市",
    code: 5405,
    parent_code: 54,
    pinyin_prefix: "s",
  },
  {
    name: "那曲市",
    code: 5406,
    parent_code: 54,
    pinyin_prefix: "n",
  },
  {
    name: "阿里地区",
    code: 5425,
    parent_code: 54,
    pinyin_prefix: "a",
  },
  {
    name: "西安市",
    code: 6101,
    parent_code: 61,
    pinyin_prefix: "x",
  },
  {
    name: "铜川市",
    code: 6102,
    parent_code: 61,
    pinyin_prefix: "t",
  },
  {
    name: "宝鸡市",
    code: 6103,
    parent_code: 61,
    pinyin_prefix: "b",
  },
  {
    name: "咸阳市",
    code: 6104,
    parent_code: 61,
    pinyin_prefix: "x",
  },
  {
    name: "渭南市",
    code: 6105,
    parent_code: 61,
    pinyin_prefix: "w",
  },
  {
    name: "延安市",
    code: 6106,
    parent_code: 61,
    pinyin_prefix: "y",
  },
  {
    name: "汉中市",
    code: 6107,
    parent_code: 61,
    pinyin_prefix: "h",
  },
  {
    name: "榆林市",
    code: 6108,
    parent_code: 61,
    pinyin_prefix: "y",
  },
  {
    name: "安康市",
    code: 6109,
    parent_code: 61,
    pinyin_prefix: "a",
  },
  {
    name: "商洛市",
    code: 6110,
    parent_code: 61,
    pinyin_prefix: "s",
  },
  {
    name: "兰州市",
    code: 6201,
    parent_code: 62,
    pinyin_prefix: "l",
  },
  {
    name: "嘉峪关市",
    code: 6202,
    parent_code: 62,
    pinyin_prefix: "j",
  },
  {
    name: "金昌市",
    code: 6203,
    parent_code: 62,
    pinyin_prefix: "j",
  },
  {
    name: "白银市",
    code: 6204,
    parent_code: 62,
    pinyin_prefix: "b",
  },
  {
    name: "天水市",
    code: 6205,
    parent_code: 62,
    pinyin_prefix: "t",
  },
  {
    name: "武威市",
    code: 6206,
    parent_code: 62,
    pinyin_prefix: "w",
  },
  {
    name: "张掖市",
    code: 6207,
    parent_code: 62,
    pinyin_prefix: "z",
  },
  {
    name: "平凉市",
    code: 6208,
    parent_code: 62,
    pinyin_prefix: "p",
  },
  {
    name: "酒泉市",
    code: 6209,
    parent_code: 62,
    pinyin_prefix: "j",
  },
  {
    name: "庆阳市",
    code: 6210,
    parent_code: 62,
    pinyin_prefix: "q",
  },
  {
    name: "定西市",
    code: 6211,
    parent_code: 62,
    pinyin_prefix: "d",
  },
  {
    name: "陇南市",
    code: 6212,
    parent_code: 62,
    pinyin_prefix: "l",
  },
  {
    name: "临夏回族自治州",
    code: 6229,
    parent_code: 62,
    pinyin_prefix: "l",
  },
  {
    name: "甘南藏族自治州",
    code: 6230,
    parent_code: 62,
    pinyin_prefix: "g",
  },
  {
    name: "西宁市",
    code: 6301,
    parent_code: 63,
    pinyin_prefix: "x",
  },
  {
    name: "海东市",
    code: 6302,
    parent_code: 63,
    pinyin_prefix: "h",
  },
  {
    name: "海北藏族自治州",
    code: 6322,
    parent_code: 63,
    pinyin_prefix: "h",
  },
  {
    name: "黄南藏族自治州",
    code: 6323,
    parent_code: 63,
    pinyin_prefix: "h",
  },
  {
    name: "海南藏族自治州",
    code: 6325,
    parent_code: 63,
    pinyin_prefix: "h",
  },
  {
    name: "果洛藏族自治州",
    code: 6326,
    parent_code: 63,
    pinyin_prefix: "g",
  },
  {
    name: "玉树藏族自治州",
    code: 6327,
    parent_code: 63,
    pinyin_prefix: "y",
  },
  {
    name: "海西蒙古族藏族自治州",
    code: 6328,
    parent_code: 63,
    pinyin_prefix: "h",
  },
  {
    name: "银川市",
    code: 6401,
    parent_code: 64,
    pinyin_prefix: "y",
  },
  {
    name: "石嘴山市",
    code: 6402,
    parent_code: 64,
    pinyin_prefix: "s",
  },
  {
    name: "吴忠市",
    code: 6403,
    parent_code: 64,
    pinyin_prefix: "w",
  },
  {
    name: "固原市",
    code: 6404,
    parent_code: 64,
    pinyin_prefix: "g",
  },
  {
    name: "中卫市",
    code: 6405,
    parent_code: 64,
    pinyin_prefix: "z",
  },
  {
    name: "乌鲁木齐市",
    code: 6501,
    parent_code: 65,
    pinyin_prefix: "w",
  },
  {
    name: "克拉玛依市",
    code: 6502,
    parent_code: 65,
    pinyin_prefix: "k",
  },
  {
    name: "吐鲁番市",
    code: 6504,
    parent_code: 65,
    pinyin_prefix: "t",
  },
  {
    name: "哈密市",
    code: 6505,
    parent_code: 65,
    pinyin_prefix: "h",
  },
  {
    name: "昌吉回族自治州",
    code: 6523,
    parent_code: 65,
    pinyin_prefix: "c",
  },
  {
    name: "博尔塔拉蒙古自治州",
    code: 6527,
    parent_code: 65,
    pinyin_prefix: "b",
  },
  {
    name: "巴音郭楞蒙古自治州",
    code: 6528,
    parent_code: 65,
    pinyin_prefix: "b",
  },
  {
    name: "阿克苏地区",
    code: 6529,
    parent_code: 65,
    pinyin_prefix: "a",
  },
  {
    name: "克孜勒苏柯尔克孜自治州",
    code: 6530,
    parent_code: 65,
    pinyin_prefix: "k",
  },
  {
    name: "喀什地区",
    code: 6531,
    parent_code: 65,
    pinyin_prefix: "k",
  },
  {
    name: "和田地区",
    code: 6532,
    parent_code: 65,
    pinyin_prefix: "h",
  },
  {
    name: "伊犁哈萨克自治州",
    code: 6540,
    parent_code: 65,
    pinyin_prefix: "y",
  },
  {
    name: "塔城地区",
    code: 6542,
    parent_code: 65,
    pinyin_prefix: "t",
  },
  {
    name: "阿勒泰地区",
    code: 6543,
    parent_code: 65,
    pinyin_prefix: "a",
  },
  {
    name: "石河子市",
    code: 659001,
    parent_code: 65,
    pinyin_prefix: "s",
  },
  {
    name: "阿拉尔市",
    code: 659002,
    parent_code: 65,
    pinyin_prefix: "a",
  },
  {
    name: "图木舒克市",
    code: 659003,
    parent_code: 65,
    pinyin_prefix: "t",
  },
  {
    name: "五家渠市",
    code: 659004,
    parent_code: 65,
    pinyin_prefix: "w",
  },
  {
    name: "北屯市",
    code: 659005,
    parent_code: 65,
    pinyin_prefix: "b",
  },
  {
    name: "铁门关市",
    code: 659006,
    parent_code: 65,
    pinyin_prefix: "t",
  },
  {
    name: "双河市",
    code: 659007,
    parent_code: 65,
    pinyin_prefix: "s",
  },
  {
    name: "可克达拉市",
    code: 659008,
    parent_code: 65,
    pinyin_prefix: "k",
  },
  {
    name: "昆玉市",
    code: 659009,
    parent_code: 65,
    pinyin_prefix: "k",
  },
  {
    name: "胡杨河市",
    code: 659010,
    parent_code: 65,
    pinyin_prefix: "h",
  },
  {
    name: "新星市",
    code: 659011,
    parent_code: 65,
    pinyin_prefix: "x",
  },
  {
    name: "台北市",
    code: 7101,
    parent_code: 71,
    pinyin_prefix: "t",
  },
  {
    name: "高雄市",
    code: 7102,
    parent_code: 71,
    pinyin_prefix: "g",
  },
  {
    name: "台南市",
    code: 7103,
    parent_code: 71,
    pinyin_prefix: "t",
  },
  {
    name: "台中市",
    code: 7104,
    parent_code: 71,
    pinyin_prefix: "t",
  },
  {
    name: "南投县",
    code: 7106,
    parent_code: 71,
    pinyin_prefix: "n",
  },
  {
    name: "基隆市",
    code: 7107,
    parent_code: 71,
    pinyin_prefix: "j",
  },
  {
    name: "新竹市",
    code: 7108,
    parent_code: 71,
    pinyin_prefix: "x",
  },
  {
    name: "嘉义市",
    code: 7109,
    parent_code: 71,
    pinyin_prefix: "j",
  },
  {
    name: "新北市",
    code: 7111,
    parent_code: 71,
    pinyin_prefix: "x",
  },
  {
    name: "宜兰县",
    code: 7112,
    parent_code: 71,
    pinyin_prefix: "y",
  },
  {
    name: "新竹县",
    code: 7113,
    parent_code: 71,
    pinyin_prefix: "x",
  },
  {
    name: "桃园市",
    code: 7114,
    parent_code: 71,
    pinyin_prefix: "t",
  },
  {
    name: "苗栗县",
    code: 7115,
    parent_code: 71,
    pinyin_prefix: "m",
  },
  {
    name: "彰化县",
    code: 7117,
    parent_code: 71,
    pinyin_prefix: "z",
  },
  {
    name: "嘉义县",
    code: 7119,
    parent_code: 71,
    pinyin_prefix: "j",
  },
  {
    name: "云林县",
    code: 7121,
    parent_code: 71,
    pinyin_prefix: "y",
  },
  {
    name: "屏东县",
    code: 7124,
    parent_code: 71,
    pinyin_prefix: "p",
  },
  {
    name: "台东县",
    code: 7125,
    parent_code: 71,
    pinyin_prefix: "t",
  },
  {
    name: "花莲县",
    code: 7126,
    parent_code: 71,
    pinyin_prefix: "h",
  },
  {
    name: "澎湖县",
    code: 7127,
    parent_code: 71,
    pinyin_prefix: "p",
  },
  {
    name: "香港特别行政区",
    code: 8100,
    parent_code: 81,
    pinyin_prefix: "x",
  },
  {
    name: "澳门特别行政区",
    code: 8200,
    parent_code: 82,
    pinyin_prefix: "a",
  },
]

export const bedroom: SelectOption[] = [
  { label: "1室", value: 1 },
  { label: "2室", value: 2 },
  { label: "3室", value: 3 },
  { label: "4室", value: 4 },
  { label: "5室", value: 5 },
  { label: "6室", value: 6 },
]

export const livingRoom: SelectOption[] = [
  { label: "0厅", value: 0 },
  { label: "1厅", value: 1 },
  { label: "2厅", value: 2 },
  { label: "3厅", value: 3 },
  { label: "4厅", value: 4 },
  { label: "5厅", value: 5 },
]

export const bathroom: SelectOption[] = [
  { label: "0卫", value: 0 },
  { label: "1卫", value: 1 },
  { label: "2卫", value: 2 },
  { label: "3卫", value: 3 },
  { label: "4卫", value: 4 },
  { label: "5卫", value: 5 },
]

export const kitchen: SelectOption[] = [
  { label: "0厨", value: 0 },
  { label: "1厨", value: 1 },
  { label: "2厨", value: 2 },
  { label: "3厨", value: 3 },
  { label: "4厨", value: 4 },
  { label: "5厨", value: 5 },
]

export const tenant: SelectOption[] = [
  { label: "2户", value: 2 },
  { label: "3户", value: 3 },
  { label: "4户", value: 4 },
  { label: "5户", value: 5 },
  { label: "6户", value: 6 },
  { label: "7户", value: 7 },
  { label: "8户", value: 8 },
  { label: "9户", value: 9 },
]
